# Generated by Django 4.0.4 on 2022-06-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RolePerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('value', models.BooleanField(blank=True, default=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('value', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'unique_together': {('app', 'code')},
            },
        ),
    ]
